### ISSUE TITLE
Not working with storybook 7.0.10

### ISSUE THREAD

**Issue by s0n4** [socheatsok78/storybook-addon-vuetify#7]
So i am currently setting up a new storybook with version 7 and it seems like this plugin can not handle some necessary imports anymore.

I get the following errors:
```node_modules/@socheatsok78/storybook-addon-vuetify/dist/decorators/withThemeProvider.js:8:42: ERROR: Could not resolve "vue"
ERR! node_modules/@socheatsok78/storybook-addon-vuetify/dist/decorators/withThemeProvider.js:12:8: ERROR: Could not resolve "vuetify/dist/vuetify.min.css"
ERR! node_modules/@socheatsok78/storybook-addon-vuetify/dist/decorators/withThemeProvider.js:14:8: ERROR: Could not resolve "@mdi/font/css/materialdesignicons.min.css"
ERR! node_modules/@socheatsok78/storybook-addon-vuetify/dist/decorators/withVuetify.js:8:42: ERROR: Could not resolve "vue"
ERR! node_modules/@socheatsok78/storybook-addon-vuetify/dist/decorators/withVuetify.js:10:46: ERROR: Could not resolve "vuetify"
```
My package.json:
```json
{
  "name": "xxx",
  "version": "0.0.0",
  "description": "Vue.js component library Storybook",
  "author": "xxx",
  "private": true,
  "files": [
    "dist",
    "CHANGELOG.md"
  ],
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "storybook": "^7.0.10",
    "vue": "^2.7.14",
    "vuetify": "2.6.15"
  },
  "devDependencies": {
    "@mdi/font": "^7.2.96",
    "@mdx-js/react": "^2.3.0",
    "@socheatsok78/storybook-addon-vuetify": "~0.1.9",
    "@storybook/addon-essentials": "^7.0.10",
    "@storybook/addon-interactions": "^7.0.10",
    "@storybook/addon-links": "^7.0.10",
    "@storybook/blocks": "^7.0.10",
    "@storybook/testing-library": "^0.0.14-next.2",
    "@storybook/vue": "^7.0.10",
    "@storybook/vue-vite": "^7.0.10",
    "@vitejs/plugin-vue2": "^2.2.0",
    "@vue/tsconfig": "^0.1.3",
    "eslint-import-resolver-typescript": "^3.5.4",
    "eslint-plugin-storybook": "~0.6.12",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vite": "^4.3.2",
    "vue-eslint-parser": "^9.1.0",
    "vue-tsc": "^1.0.24"
  },
  "packageManager": "yarn@3.4.1",
  "engines": {
    "node": ">=16.0.0"
  }
}
```
